/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author jhons
 */
public class Asignaciones extends javax.swing.JPanel {

    /**
     * Creates new form Asignaciones
     */
    public Asignaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoAsig = new javax.swing.JTextField();
        lblCodigoAsig = new javax.swing.JLabel();
        lblClienteAsig = new javax.swing.JLabel();
        txtClienteAsig = new javax.swing.JTextField();
        lblClaseAsig = new javax.swing.JLabel();
        txtClaseAsig = new javax.swing.JTextField();
        lblFechaIn = new javax.swing.JLabel();
        txtFechaIn = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        btnEliminarAsignacion = new javax.swing.JButton();
        btnActualizarAsignacion = new javax.swing.JButton();
        btnRegistrarAsignacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtCodigoAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 123, -1));

        lblCodigoAsig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCodigoAsig.setForeground(java.awt.Color.white);
        lblCodigoAsig.setText("Codigo");
        add(lblCodigoAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        lblClienteAsig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClienteAsig.setForeground(java.awt.Color.white);
        lblClienteAsig.setText("Codigo Cliente");
        add(lblClienteAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        add(txtClienteAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 123, 20));

        lblClaseAsig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClaseAsig.setForeground(java.awt.Color.white);
        lblClaseAsig.setText("Codigo Clase");
        add(lblClaseAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));
        add(txtClaseAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 123, -1));

        lblFechaIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFechaIn.setForeground(java.awt.Color.white);
        lblFechaIn.setText("Fecha Inicio");
        add(lblFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));
        add(txtFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 123, -1));

        lblFechaFin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFechaFin.setForeground(java.awt.Color.white);
        lblFechaFin.setText("Fecha Final");
        add(lblFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));
        add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 123, -1));

        btnEliminarAsignacion.setText("Eliminar Asignacion");
        add(btnEliminarAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 170, -1));

        btnActualizarAsignacion.setText("Actualizar Asignacion");
        add(btnActualizarAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 170, -1));

        btnRegistrarAsignacion.setText("Registrar Asignacion");
        add(btnRegistrarAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/asigar.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarAsignacion;
    public javax.swing.JButton btnEliminarAsignacion;
    public javax.swing.JButton btnRegistrarAsignacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblClaseAsig;
    private javax.swing.JLabel lblClienteAsig;
    private javax.swing.JLabel lblCodigoAsig;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaIn;
    public javax.swing.JTextField txtClaseAsig;
    public javax.swing.JTextField txtClienteAsig;
    public javax.swing.JTextField txtCodigoAsig;
    public javax.swing.JTextField txtFechaFin;
    public javax.swing.JTextField txtFechaIn;
    // End of variables declaration//GEN-END:variables
}
