/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Claudia
 */
public class Clases extends javax.swing.JPanel {

    /**
     * Creates new form clases
     */
    public Clases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnRegistrarClases = new javax.swing.JButton();
        btnActualizarClases = new javax.swing.JButton();
        btnCancelarClases = new javax.swing.JButton();
        cbxHorario = new javax.swing.JComboBox<>();
        txtClase = new javax.swing.JTextField();
        txtInstructor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Codigo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Clase");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Instructor");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Horario");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        txtCodigo.setName("jTxtCedula"); // NOI18N
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 130, 410, -1));

        btnRegistrarClases.setText("Registrar Clase");
        add(btnRegistrarClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 140, -1));

        btnActualizarClases.setText("Actualizar Clase");
        add(btnActualizarClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 140, -1));

        btnCancelarClases.setText("Cancelar Clase");
        add(btnCancelarClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 130, -1));

        cbxHorario.setEditable(true);
        cbxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Horario", "6:00 am - 7:00 am", "7:00 am - 8:00 am", "8:00 am - 9:00 am", "9:00 am - 10:00 am", "3:00 pm - 4:00 pm", "4:00 pm - 5:00 pm", "5:00 pm - 6:00 pm", "6:00 pm - 7:00 pm", "7:00 pm - 8:00 pm", "8:00 pm - 9:00 pm" }));
        add(cbxHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 210, 410, -1));

        txtClase.setName("jTxtClase"); // NOI18N
        add(txtClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 170, 410, -1));
        add(txtInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 410, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Imagen4.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarClases;
    public javax.swing.JButton btnCancelarClases;
    public javax.swing.JButton btnRegistrarClases;
    public javax.swing.JComboBox<String> cbxHorario;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField txtClase;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtInstructor;
    // End of variables declaration//GEN-END:variables
}
