/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Claudia
 */
public class Clientes extends javax.swing.JPanel {

    /**
     * Creates new form clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnRegistrarClientes = new javax.swing.JButton();
        btnActualizarClientes = new javax.swing.JButton();
        btnEliminarClientes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jTextField7.setText("jTextField7");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Direccion");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Telefono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Fecha");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        txtNombre.setName("jTxtNombre"); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 164, -1));

        txtApellido.setName("jTxtApellido"); // NOI18N
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 164, -1));

        txtDireccion.setName("jTxtDireccion"); // NOI18N
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 164, -1));

        txtTelefono.setName("jTxtTelefono"); // NOI18N
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 164, -1));

        txtFecha.setName("jTxtFecha"); // NOI18N
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 164, -1));

        btnRegistrarClientes.setText("Registrar Cliente");
        btnRegistrarClientes.setName("jBtnRegistrar"); // NOI18N
        add(btnRegistrarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 140, -1));

        btnActualizarClientes.setText("Actualizar Cliente");
        btnActualizarClientes.setName("jBtnActualizar"); // NOI18N
        add(btnActualizarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 140, -1));

        btnEliminarClientes.setText("Eliminar Cliente");
        btnEliminarClientes.setName("jBtnEliminar"); // NOI18N
        add(btnEliminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Cedula");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        txtCedula.setToolTipText("");
        txtCedula.setName("jTxtCedula"); // NOI18N
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 164, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Imagen3.jpg"))); // NOI18N
        jLabel7.setToolTipText("");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarClientes;
    public javax.swing.JButton btnEliminarClientes;
    public javax.swing.JButton btnRegistrarClientes;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField7;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
