/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Claudia
 */
public class Instructores extends javax.swing.JPanel {

    /**
     * Creates new form instructores
     */
    public Instructores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxJornada = new javax.swing.JComboBox<>();
        cbxHora = new javax.swing.JComboBox<>();
        cbxEspecialidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Codigo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Apellido");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Especialidad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Jornada");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        txtCodigo.setName("jTxtCodigo"); // NOI18N
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 430, -1));

        txtNombre.setName("jTxtNombre"); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 430, -1));

        txtApellido.setName("jTxtApellido"); // NOI18N
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 430, -1));

        btnConsultar.setText("Consultar Instructor");
        btnConsultar.setName("jBtnConsultar"); // NOI18N
        add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 170, -1));

        btnRegistrar.setText("Registrar Instructor");
        btnRegistrar.setName("jBtnRegistrar"); // NOI18N
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 170, -1));

        btnActualizar.setText("Actualizar Instructor");
        btnActualizar.setName("jBtnActualizar"); // NOI18N
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 170, -1));

        btnEliminar.setText("Eliminar Instructor");
        btnEliminar.setName("jBtnEliminar"); // NOI18N
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Telefono");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtTelefono.setName("jTxtTelefono"); // NOI18N
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 430, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Horario");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        cbxJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Jornada", "Mañana", "Tarde" }));
        add(cbxJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 430, -1));

        cbxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Horario", "6:00 am - 7:00 am", "7:00 am - 8:00 am", "8:00 am - 9:00 am", "9:00 am - 10:00 am", "3:00 pm - 4:00 pm", "4:00 pm - 5:00 pm", "5:00 pm - 6:00 pm", "6:00 pm - 7:00 pm", "7:00 pm - 8:00 pm", "8:00 pm - 9:00 pm" }));
        add(cbxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 430, -1));

        cbxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Especialidad", "Yoga", "Aquaerobics", "Bailoterapia", "Bodycombat", "Entrenamiento funcional", "Spinning" }));
        add(cbxEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 430, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Imagen5.jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JComboBox<String> cbxEspecialidad;
    public javax.swing.JComboBox<String> cbxHora;
    public javax.swing.JComboBox<String> cbxJornada;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
